// GENERATED by tool/gen_tiers.mjs from lib/data/card_theme.dart. Do not edit.
export type TierGradient = { angleDeg: number; stops: [string, number][] };

export interface TierTheme {
  bg: TierGradient;
  bgLight: TierGradient;
  accent: string;
  accentLight: string;
  labelBg: string;
  label: string;
  emoji: string;
}

export const tierThemes: Record<number, TierTheme> = {
  1: {
    bg: { angleDeg: 160, stops: [['#3b1f00', 0], ['#1a0d00', 100]] },
    bgLight: { angleDeg: 160, stops: [['#efdcc2', 0], ['#e0c9a0', 100]] },
    accent: '#8B5A00',
    accentLight: '#C87F2A',
    labelBg: '#3d2000',
    label: "Bronze",
    emoji: "🟫",
  },
  2: {
    bg: { angleDeg: 160, stops: [['#4a2800', 0], ['#261400', 100]] },
    bgLight: { angleDeg: 160, stops: [['#ecd2b0', 0], ['#d9bd8e', 100]] },
    accent: '#A06820',
    accentLight: '#D4943A',
    labelBg: '#4a2800',
    label: "Bronze+",
    emoji: "🟤",
  },
  3: {
    bg: { angleDeg: 160, stops: [['#252525', 0], ['#111', 100]] },
    bgLight: { angleDeg: 160, stops: [['#ededed', 0], ['#d6d6d6', 100]] },
    accent: '#888888',
    accentLight: '#bbbbbb',
    labelBg: '#2a2a2a',
    label: "Silver",
    emoji: "⚪",
  },
  4: {
    bg: { angleDeg: 160, stops: [['#2d2d2d', 0], ['#181818', 100]] },
    bgLight: { angleDeg: 160, stops: [['#f1f1f1', 0], ['#dcdcdc', 100]] },
    accent: '#999999',
    accentLight: '#cccccc',
    labelBg: '#333333',
    label: "Silver★",
    emoji: "🔘",
  },
  5: {
    bg: { angleDeg: 160, stops: [['#3a2a00', 0], ['#1a1200', 100]] },
    bgLight: { angleDeg: 160, stops: [['#f3e6b0', 0], ['#e6d28a', 100]] },
    accent: '#C8960C',
    accentLight: '#FFD440',
    labelBg: '#3d2e00',
    label: "Gold",
    emoji: "🟡",
  },
  6: {
    bg: { angleDeg: 160, stops: [['#4a3600', 0], ['#241b00', 100]] },
    bgLight: { angleDeg: 160, stops: [['#f5e4a0', 0], ['#ead07e', 100]] },
    accent: '#FFB300',
    accentLight: '#FFD740',
    labelBg: '#4a3800',
    label: "Gold★",
    emoji: "🟠",
  },
  7: {
    bg: { angleDeg: 160, stops: [['#1f004a', 0], ['#0d0025', 100]] },
    bgLight: { angleDeg: 160, stops: [['#e6d2f5', 0], ['#d2b0ec', 100]] },
    accent: '#A040F0',
    accentLight: '#C880FF',
    labelBg: '#2a0060',
    label: "Legend",
    emoji: "🟣",
  },
  8: {
    bg: { angleDeg: 135, stops: [['#001a40', 0], ['#003366', 50], ['#000820', 100]] },
    bgLight: { angleDeg: 135, stops: [['#cfe8f5', 0], ['#bfe0f0', 50], ['#d6eef8', 100]] },
    accent: '#00c8ff',
    accentLight: '#80e8ff',
    labelBg: '#001830',
    label: "World Class",
    emoji: "🌟",
  },
  9: {
    bg: { angleDeg: 135, stops: [['#1a0a00', 0], ['#3d1f00', 30], ['#000820', 70], ['#1a0040', 100]] },
    bgLight: { angleDeg: 135, stops: [['#f5e2c2', 0], ['#f0d2a0', 30], ['#d6e2f5', 70], ['#e0d2f5', 100]] },
    accent: '#ffaa00',
    accentLight: '#ffe066',
    labelBg: '#1a0800',
    label: "⚡ Icon",
    emoji: "⚡",
  },
};

/** The tier body as a CSS gradient. Stops are percentages in the catalogue. */
export const tierGradientCss = (g: TierGradient): string =>
  `linear-gradient(${g.angleDeg}deg, ${g.stops.map(([c, at]) => `${c} ${at}%`).join(', ')})`;
