// GENERATED by tool/gen_keeper_art.mjs — do not edit.
// Source: ../merge-empire-fc/src/ui/components/PenaltyGame.js

/// The penalty keeper, one illustration per kit tier.
///
/// The tier comes from the DIVISION — see `keeperTierForDivision` — so the
/// keeper a player faces in the Champions Cup is visibly not the one they beat
/// in Sunday League. Drawn by `ui/widgets/svg_canvas.dart`.
///
/// The number on the shirt IS the tier, which is the JS's own joke and the
/// reason these are eight strings rather than one string and a palette.
library;

/// The space he is drawn in.
const double keeperArtWidth = 160;
const double keeperArtHeight = 240;

const Map<int, String> keeperArt = {
  1: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b88700" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b88700" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    1
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  2: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b88700" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b88700" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    2
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  3: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#c0c0c0"/>
      <stop offset="1" stop-color="#666"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#c0c0c0"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#c0c0c0"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#666" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#666" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    3
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  4: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#90a4ae"/>
      <stop offset="1" stop-color="#455a64"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#263238"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#90a4ae"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#263238"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#90a4ae"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#263238"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#455a64" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#455a64" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    4
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  5: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff9800"/>
      <stop offset="1" stop-color="#b86b00"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ff9800"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ff9800"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b86b00" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b86b00" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    5
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  6: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff6d00"/>
      <stop offset="1" stop-color="#b85400"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#212121"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ff6d00"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#212121"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ff6d00"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#212121"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b85400" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b85400" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    6
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  7: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b06aff"/>
      <stop offset="1" stop-color="#6a1b9a"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a0040"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#b06aff"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a0040"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#b06aff"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a0040"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#6a1b9a" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#6a1b9a" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    7
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
  8: '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a237e"/>
      <stop offset="1" stop-color="#ffd700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  <g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#0a0a38"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#1a237e"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>
  <!-- Right leg -->
  <g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#0a0a38"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#1a237e"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g>

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#0a0a38"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#ffd700" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#ffd700" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    8
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  <g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>
  <g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g>

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
};

/// The joints the four limbs turn about, in the art's own space.
///
/// Straight out of `screens.css`, which sets a `transform-origin` per group:
/// a limb rotated about anything else swings out of its own socket.
const Map<String, (double x, double y)> keeperJoints = {
  'armL': (44, 84),
  'armR': (116, 84),
  'legL': (64, 162),
  'legR': (96, 162),
};

/// One tier of keeper, cut into the pieces the rig turns.
typedef KeeperLayers = ({
  String body,
  String armL,
  String armR,
  String legL,
  String legR,
});

const Map<int, KeeperLayers> keeperLayers = {
  1: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b88700" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b88700" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    1
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  2: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b88700" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b88700" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    2
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#2e7d32"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffcc33"/>
      <stop offset="1" stop-color="#b88700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ffcc33"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  3: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#c0c0c0"/>
      <stop offset="1" stop-color="#666"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#666" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#666" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    3
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#c0c0c0"/>
      <stop offset="1" stop-color="#666"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#c0c0c0"/>
      <stop offset="1" stop-color="#666"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#c0c0c0"/>
      <stop offset="1" stop-color="#666"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#c0c0c0"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#c0c0c0"/>
      <stop offset="1" stop-color="#666"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#c0c0c0"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  4: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#90a4ae"/>
      <stop offset="1" stop-color="#455a64"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#263238"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#455a64" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#455a64" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    4
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#90a4ae"/>
      <stop offset="1" stop-color="#455a64"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#90a4ae"/>
      <stop offset="1" stop-color="#455a64"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#e53935"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#90a4ae"/>
      <stop offset="1" stop-color="#455a64"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#263238"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#90a4ae"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#90a4ae"/>
      <stop offset="1" stop-color="#455a64"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#263238"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#90a4ae"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  5: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff9800"/>
      <stop offset="1" stop-color="#b86b00"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a1a1a"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b86b00" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b86b00" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    5
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff9800"/>
      <stop offset="1" stop-color="#b86b00"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff9800"/>
      <stop offset="1" stop-color="#b86b00"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff9800"/>
      <stop offset="1" stop-color="#b86b00"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ff9800"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff9800"/>
      <stop offset="1" stop-color="#b86b00"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a1a1a"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ff9800"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  6: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff6d00"/>
      <stop offset="1" stop-color="#b85400"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#212121"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#b85400" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#b85400" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    6
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff6d00"/>
      <stop offset="1" stop-color="#b85400"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff6d00"/>
      <stop offset="1" stop-color="#b85400"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#212121"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff6d00"/>
      <stop offset="1" stop-color="#b85400"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#212121"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#ff6d00"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ff6d00"/>
      <stop offset="1" stop-color="#b85400"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#212121"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#ff6d00"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  7: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b06aff"/>
      <stop offset="1" stop-color="#6a1b9a"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#1a0040"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#6a1b9a" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#6a1b9a" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    7
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b06aff"/>
      <stop offset="1" stop-color="#6a1b9a"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b06aff"/>
      <stop offset="1" stop-color="#6a1b9a"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b06aff"/>
      <stop offset="1" stop-color="#6a1b9a"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#1a0040"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#b06aff"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b06aff"/>
      <stop offset="1" stop-color="#6a1b9a"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#1a0040"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#b06aff"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
  8: (
    body:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;display:block;">
  <defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a237e"/>
      <stop offset="1" stop-color="#ffd700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs>

  <!-- Shadow under keeper -->
  <ellipse cx="80" cy="232" rx="40" ry="5" fill="rgba(0,0,0,0.35)"/>

  <!-- Legs: slight knee-bend ready stance. Each wrapped in a pivot group so
       CSS can rotate them independently at the hip during dives/falls. -->
  <!-- Left leg -->
  
  <!-- Right leg -->
  

  <!-- Shorts hem darker to separate from torso -->
  <rect x="50" y="152" width="60" height="16" rx="5" fill="#0a0a38"/>
  <rect x="50" y="160" width="60" height="3" fill="rgba(255,255,255,0.1)"/>

  <!-- Torso (jersey) -->
  <path d="M44 78 Q80 64 116 78 L120 160 Q80 172 40 160 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>

  <!-- Jersey trim: shoulder stripes + central band -->
  <path d="M44 78 Q60 72 76 78 L76 92 Q60 86 44 92 Z" fill="#ffd700" opacity="0.7"/>
  <path d="M84 78 Q100 72 116 78 L116 92 Q100 86 84 92 Z" fill="#ffd700" opacity="0.7"/>

  <!-- Collar v-neck -->
  <path d="M66 68 L80 82 L94 68 L90 66 L80 76 L70 66 Z" fill="#1a1a1a"/>

  <!-- Jersey number -->
  <text x="80" y="130" text-anchor="middle" font-family="Arial Black, Impact, sans-serif"
        font-size="28" font-weight="900" fill="#fff" stroke="#1a1a1a" stroke-width="1.2">
    8
  </text>

  <!-- Arms out to the sides (ready stance), elbow slightly bent.
       Each arm + glove is wrapped in a group so the parent .pen-keeper can
       pivot it via CSS during a dive (see .dive-left / .dive-right rules). -->
  
  

  <!-- Neck -->
  <rect x="72" y="60" width="16" height="10" fill="url(#kg-skin)"/>

  <!-- Head: rounded, slightly squared jaw -->
  <path d="M60 46 Q60 24 80 22 Q100 24 100 46 L98 58 Q80 68 62 58 Z"
        fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1.5"/>

  <!-- Hair: short sides + slight fringe -->
  <path d="M60 42 Q60 22 80 20 Q100 22 100 42 Q96 34 80 32 Q64 34 60 42 Z" fill="#3b2a1a"/>

  <!-- Ears -->
  <ellipse cx="58" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>
  <ellipse cx="102" cy="46" rx="3" ry="5" fill="url(#kg-skin)" stroke="#6a4820" stroke-width="1"/>

  <!-- Eyes: small but detailed -->
  <ellipse cx="72" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <ellipse cx="88" cy="44" rx="3.2" ry="2.2" fill="#fff" stroke="#1a1a1a" stroke-width="0.8"/>
  <circle cx="72" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <circle cx="88" cy="44.5" r="1.3" fill="#1a1a1a"/>
  <!-- Eyebrows (slight scowl — focused) -->
  <path d="M67 39 Q72 37 77 40" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>
  <path d="M83 40 Q88 37 93 39" stroke="#1a1a1a" stroke-width="1.8" fill="none" stroke-linecap="round"/>

  <!-- Nose -->
  <path d="M80 46 L78 54 L82 54 Z" fill="rgba(0,0,0,0.1)"/>

  <!-- Mouth: determined straight line -->
  <line x1="73" y1="58" x2="87" y2="58" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
</svg>''',
    armL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a237e"/>
      <stop offset="1" stop-color="#ffd700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-l">
    <path d="M44 84 Q24 96 14 118 L26 124 Q38 108 54 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="4"   y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="10" y1="112" x2="10" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="16" y1="112" x2="16" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="22" y1="112" x2="22" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="6" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    armR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a237e"/>
      <stop offset="1" stop-color="#ffd700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-arm-r">
    <path d="M116 84 Q136 96 146 118 L134 124 Q122 108 106 98 Z" fill="url(#kg-jersey)" stroke="#1a1a1a" stroke-width="2"/>
    <rect x="130" y="108" width="26" height="22" rx="8" stroke="#1a1a1a" stroke-width="2" fill="#ffd700"/>
    <line x1="138" y1="112" x2="138" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="144" y1="112" x2="144" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <line x1="150" y1="112" x2="150" y2="128" stroke="rgba(0,0,0,0.35)" stroke-width="1"/>
    <rect x="132" y="126" width="22" height="6" rx="2" fill="#1a1a1a"/>
  </g></svg>''',
    legL:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a237e"/>
      <stop offset="1" stop-color="#ffd700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-l">
    <rect x="54" y="160" width="20" height="52" rx="7" fill="#0a0a38"/>
    <rect x="54" y="192" width="20" height="24" rx="6" fill="#1a237e"/>
    <ellipse cx="64" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
    legR:
        '''<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg"><defs>
    <linearGradient id="kg-jersey" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a237e"/>
      <stop offset="1" stop-color="#ffd700"/>
    </linearGradient>
    <radialGradient id="kg-skin">
      <stop offset="0" stop-color="#f5cda0"/>
      <stop offset="1" stop-color="#d9a877"/>
    </radialGradient>
  </defs><g class="k-leg-r">
    <rect x="86" y="160" width="20" height="52" rx="7" fill="#0a0a38"/>
    <rect x="86" y="192" width="20" height="24" rx="6" fill="#1a237e"/>
    <ellipse cx="96" cy="222" rx="14" ry="6" fill="#0a0a0a"/>
  </g></svg>''',
  ),
};
