/// Every hat and every beard actually lands on his head.
///
/// **THREE ROWS OF THE ANDROID QUEUE ARE THIS ONE QUESTION** — the headband,
/// the laurel and "be careful of the facial hairs, each needs measuring against
/// the face, some of them don't stay on the face" — and all three were being
/// carried as blocked on the spec repo, because `manager_art.g.dart` is
/// generated from `../merge-empire-fc` and its SHAPES cannot be changed from
/// here. That is true of the shapes and it is not true of the PLACEMENT, which
/// is measurable from this repo and was only ever believed rather than proved.
///
/// So this proves it, and keeps proving it: the art is regenerated by
/// `tool/gen_manager_art.mjs` and nothing before this failed the build when a
/// regenerated hat came back sitting beside his ear.
///
/// **Measured through the PRODUCTION renderer**, not a parser written for the
/// test. Each part is painted by `SvgArt` — the same widget the walker uses —
/// into its own 120x170 art space, and the bounding box of everything with any
/// alpha in it is read back off the pixels. A test-only SVG parser is a second
/// implementation of the thing under test, and the first attempt at one here
/// reported the same bogus outlier for all nine beards.
library;

import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:merge_empire_fc/data/manager_art.g.dart';
import 'package:merge_empire_fc/data/manager_looks.dart' show hatCrownY;
import 'package:merge_empire_fc/ui/screens/home/manager_walker.dart'
    show skullInArt, skullRadius;
import 'package:merge_empire_fc/ui/widgets/svg_canvas.dart';

/// Four device pixels per art unit, so a quarter-unit edge is measurable.
const double _scale = 4;

/// The skull the art is drawn against: a circle at (62, 48.5) with r 12.5, so
/// it spans x 49.5..74.5 and y 36..61. The chin reaches a shade below.
double get _left => skullInArt.dx - skullRadius;
double get _right => skullInArt.dx + skullRadius;
double get _crown => skullInArt.dy - skullRadius;
double get _chin => skullInArt.dy + skullRadius;

void main() {
  /// What the part actually paints, in art units. Null when it paints nothing,
  /// which `none` legitimately does.
  Future<Rect?> painted(WidgetTester tester, String svg) async {
    if (svg.isEmpty) return null;
    final key = GlobalKey();
    await tester.pumpWidget(
      MaterialApp(
        home: Center(
          child: RepaintBoundary(
            key: key,
            child: SizedBox(
              width: managerArtWidth,
              height: managerArtHeight,
              child: SvgArt(svg: svg),
            ),
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    Rect? box;
    await tester.runAsync(() async {
      final boundary =
          key.currentContext!.findRenderObject()! as RenderRepaintBoundary;
      final image = await boundary.toImage(pixelRatio: _scale);
      final data = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
      final bytes = data!.buffer.asUint8List();
      var minX = double.infinity, minY = double.infinity;
      var maxX = double.negativeInfinity, maxY = double.negativeInfinity;
      for (var y = 0; y < image.height; y++) {
        for (var x = 0; x < image.width; x++) {
          // A faint anti-aliased edge is not the shape; 24/255 skips the fringe
          // without eating a soft stroke.
          if (bytes[(y * image.width + x) * 4 + 3] <= 24) continue;
          if (x < minX) minX = x.toDouble();
          if (x > maxX) maxX = x.toDouble();
          if (y < minY) minY = y.toDouble();
          if (y > maxY) maxY = y.toDouble();
        }
      }
      if (maxX < 0) return;
      box = Rect.fromLTRB(
        minX / _scale,
        minY / _scale,
        maxX / _scale,
        maxY / _scale,
      );
    });
    return box;
  }

  group('EVERY HAT SITS ON HIS HEAD', () {
    testWidgets('it reaches the crown, and it stops at the brow', (
      tester,
    ) async {
      for (final entry in managerHats.entries) {
        final box = await painted(tester, entry.value);
        if (box == null) {
          expect(entry.key, 'none', reason: 'a hat that draws nothing');
          continue;
        }
        final why = entry.key;
        // The top of every hat is at or above the crown: a hat that started
        // below it would be a band round his face.
        expect(box.top, lessThanOrEqualTo(_crown), reason: why);
        // And the bottom stops on the upper half of the head. The exception is
        // the headphones, which are one earpiece hanging by the ear — the only
        // hat in the set that is not worn on top.
        expect(
          box.bottom,
          lessThanOrEqualTo(why == 'headphones' ? 56 : 48),
          reason: why,
        );
      }
    });

    testWidgets('and it is worn straight, not over one ear', (tester) async {
      // The furthest off-centre is the Santa hat at 4.7 units, which is its
      // tail hanging one way, and the peaked ones — cap, visor, flatcap,
      // hardhat — lean about 3 the other because their peaks point the way he
      // faces. Both are the drawing doing what it means to.
      for (final entry in managerHats.entries) {
        final box = await painted(tester, entry.value);
        if (box == null) continue;
        expect(
          (box.center.dx - skullInArt.dx).abs(),
          lessThan(5.5),
          reason: '${entry.key} is not on straight',
        );
      }
    });

    testWidgets('THE BANDS ARE BANDS, and they are the ones that hide nothing', (
      tester,
    ) async {
      // `hatCrownY` is null for the four that sit AROUND the head rather than
      // on top of it, and clipping hair for those would shave the top off his
      // head. This is the other half of that decision: a band has to be shallow.
      for (final entry in managerHats.entries) {
        if (hatCrownY[entry.key] != null || entry.key == 'none') continue;
        final box = await painted(tester, entry.value);
        if (box == null) continue;
        expect(
          box.height,
          lessThan(21),
          reason: '${entry.key} is deep enough to be a crown, not a band',
        );
      }
    });
  });

  group('AND EVERY BEARD STAYS ON HIS FACE', () {
    testWidgets('none of it drifts off the sides of the skull', (tester) async {
      // The row: "some of them don't stay on the face or are slightly wrong
      // position". Measured, every one of them is inside the skull's own
      // horizontal span — the widest reaches 74.0 against a right edge of 74.5,
      // and the leftmost is muttonchops at exactly 49.5.
      for (final entry in managerBeards.entries) {
        final box = await painted(tester, entry.value);
        if (box == null) {
          expect(entry.key, 'none');
          continue;
        }
        expect(box.left, greaterThanOrEqualTo(_left - 0.5), reason: entry.key);
        expect(box.right, lessThanOrEqualTo(_right + 0.5), reason: entry.key);
      }
    });

    testWidgets('and none of it starts above the eyeline', (tester) async {
      // A beard is drawn on the lower face. Muttonchops are the highest, and
      // they start at the temple at y42 because that is where a sideburn
      // starts; everything else begins at 50 or below, which is the skull's
      // own centre line.
      for (final entry in managerBeards.entries) {
        final box = await painted(tester, entry.value);
        if (box == null) continue;
        expect(
          box.top,
          greaterThanOrEqualTo(entry.key == 'muttonchops' ? 41 : 49),
          reason: entry.key,
        );
      }
    });

    testWidgets('TWO OF THEM HANG BELOW THE CHIN, and it is these two', (
      tester,
    ) async {
      // The one open question the earlier measurement left: `full` and
      // `braided` reach y72.8, about twelve units under a chin at y61 — which
      // is a long beard rather than a misplaced one. Naming them is what makes
      // that a decision rather than a shrug: if a regenerated set produces a
      // THIRD one down there, or moves one of these onto the collar, the build
      // says so.
      final hanging = <String>[];
      for (final entry in managerBeards.entries) {
        final box = await painted(tester, entry.value);
        if (box == null) continue;
        if (box.bottom > _chin + 1) hanging.add(entry.key);
        // And nothing reaches the shoulders, wherever the chin is.
        expect(box.bottom, lessThan(74), reason: entry.key);
      }
      expect(hanging, ['full', 'braided']);
    });
  });
}
