// Captures the penalty keeper as data, one string per kit tier.
//
// `ui/components/PenaltyGame.js` draws him as a full SVG illustration —
// proportions, jersey gradient, shoulder trim, v-neck, the tier number on the
// shirt, padded gloves with finger seams, ears, eyes, eyebrows, a set mouth —
// and picks the palette from the DIVISION, so a Champions Cup keeper visibly is
// not a Sunday League one. The port had drawn five flat rectangles instead.
//
// Same kind of port as the club and manager art: the strings come across
// verbatim and `ui/widgets/svg_canvas.dart` draws them. This one is read out of
// a UI component rather than a data module, so it is extracted from the SOURCE
// TEXT: the component imports the DOM and cannot be imported under node.
//
// Two substitutions, both the template's own: the palette entry for the tier,
// and the tier number that goes on the shirt.
//
//   node tool/gen_keeper_art.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const SRC = '../merge-empire-fc/src/ui/components/PenaltyGame.js';
const OUT = 'lib/data/keeper_art.g.dart';

const source = readFileSync(SRC, 'utf8');

// ── The palette ─────────────────────────────────────────────────────────────
// A plain object literal, so it is read back with a Function rather than a
// hand-rolled parser. Bounded to the literal itself: anything else in the file
// would be a syntax error here rather than a silent misread.
const paletteMatch = source.match(
  /const KEEPER_PALETTE = (\{[\s\S]*?\n\});/,
);
if (!paletteMatch) throw new Error('KEEPER_PALETTE not found in ' + SRC);
const palette = new Function(`return ${paletteMatch[1]}`)();

// ── The template ────────────────────────────────────────────────────────────
const start = source.indexOf('const buildKeeperSvg');
if (start < 0) throw new Error('buildKeeperSvg not found in ' + SRC);
const open = source.indexOf('return `', start);
const close = source.indexOf('`;', open + 8);
if (open < 0 || close < 0) throw new Error('buildKeeperSvg template not found');
const template = source.slice(open + 8, close);

// Every placeholder the template uses. Listed rather than regexed out, so a
// template that grows a new one fails here instead of shipping `${p.boots}`
// into the artwork.
const KEYS = ['jersey', 'trim', 'shorts', 'glove', 'socks'];

const svgFor = (tier) => {
  const p = palette[tier] ?? palette[3];
  let out = template;
  for (const key of KEYS) {
    out = out.split('${p.' + key + '}').join(p[key]);
  }
  out = out.split('${tierNum}').join(String(Math.max(1, Math.min(8, tier))));
  if (out.includes('${')) {
    throw new Error(`unsubstituted placeholder for tier ${tier}`);
  }
  return out.trim();
};

// ── The rig ─────────────────────────────────────────────────────────────────
// The JS wraps each arm and each leg in a `<g class="k-...">` precisely so CSS
// can rotate it about a named joint, and `screens.css` gives the four pivots.
// The port rotates the same five pieces with Flutter's own animated transforms,
// which needs them as separate strings — a flat SVG cannot have one limb turned.
//
// Every layer carries the `<defs>` block: the sleeves are painted with the
// jersey gradient, and a layer that left the definition behind would draw an
// unpainted arm.
const LIMB_CLASSES = ['k-arm-l', 'k-arm-r', 'k-leg-l', 'k-leg-r'];

const defsOf = (svg) => {
  const m = svg.match(/<defs>[\s\S]*?<\/defs>/);
  return m ? m[0] : '';
};

const groupOf = (svg, cls) => {
  const open = svg.indexOf(`<g class="${cls}">`);
  if (open < 0) throw new Error(`group ${cls} not found`);
  const close = svg.indexOf('</g>', open);
  if (close < 0) throw new Error(`group ${cls} unterminated`);
  return svg.slice(open, close + 4);
};

const HEADER =
  '<svg viewBox="0 0 160 240" xmlns="http://www.w3.org/2000/svg">';

/// The five pieces: the body with its limbs cut out, and each limb on its own.
const layersOf = (svg) => {
  const defs = defsOf(svg);
  const limbs = {};
  let body = svg;
  for (const cls of LIMB_CLASSES) {
    const group = groupOf(svg, cls);
    limbs[cls] = `${HEADER}${defs}${group}</svg>`;
    body = body.split(group).join('');
  }
  return { body: body.trim(), ...limbs };
};

const tiers = Object.keys(palette)
  .map(Number)
  .sort((a, b) => a - b);

const lines = [
  '// GENERATED by tool/gen_keeper_art.mjs — do not edit.',
  '// Source: ../merge-empire-fc/src/ui/components/PenaltyGame.js',
  '',
  "/// The penalty keeper, one illustration per kit tier.",
  '///',
  '/// The tier comes from the DIVISION — see `keeperTierForDivision` — so the',
  '/// keeper a player faces in the Champions Cup is visibly not the one they beat',
  '/// in Sunday League. Drawn by `ui/widgets/svg_canvas.dart`.',
  '///',
  '/// The number on the shirt IS the tier, which is the JS\'s own joke and the',
  '/// reason these are eight strings rather than one string and a palette.',
  'library;',
  '',
  '/// The space he is drawn in.',
  'const double keeperArtWidth = 160;',
  'const double keeperArtHeight = 240;',
  '',
  'const Map<int, String> keeperArt = {',
];

for (const tier of tiers) {
  lines.push(`  ${tier}: '''${svgFor(tier)}''',`);
}
lines.push('};', '');

lines.push(
  "/// The joints the four limbs turn about, in the art's own space.",
  '///',
  "/// Straight out of `screens.css`, which sets a `transform-origin` per group:",
  '/// a limb rotated about anything else swings out of its own socket.',
  'const Map<String, (double x, double y)> keeperJoints = {',
  "  'armL': (44, 84),",
  "  'armR': (116, 84),",
  "  'legL': (64, 162),",
  "  'legR': (96, 162),",
  '};',
  '',
  '/// One tier of keeper, cut into the pieces the rig turns.',
  'typedef KeeperLayers = ({',
  '  String body,',
  '  String armL,',
  '  String armR,',
  '  String legL,',
  '  String legR,',
  '});',
  '',
  'const Map<int, KeeperLayers> keeperLayers = {',
);
for (const tier of tiers) {
  const l = layersOf(svgFor(tier));
  lines.push(
    `  ${tier}: (`,
    `    body: '''${l.body}''',`,
    `    armL: '''${l['k-arm-l']}''',`,
    `    armR: '''${l['k-arm-r']}''',`,
    `    legL: '''${l['k-leg-l']}''',`,
    `    legR: '''${l['k-leg-r']}''',`,
    '  ),',
  );
}
lines.push('};', '');

writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${OUT} — ${tiers.length} tiers`);
