// Captures the manager avatar's parts as data.
//
// `data/managerAvatar.js` holds every hairstyle, beard, hat, outfit overlay and
// neck item as an SVG FRAGMENT — a bare `<path>` or two with no wrapper — all
// drawn in one shared space so they stack into a figure. Same kind of port as
// the club art and the i18n catalogues: the strings come across verbatim and
// `ui/widgets/svg_canvas.dart` draws them, rather than thirty-odd shapes being
// transcribed into Dart by eye.
//
// TWO THINGS ARE RESOLVED on the way out, and both have to be:
//
//   * CSS custom properties become their fallbacks. The fragments paint with
//     `var(--hair, #3a2a1c)` so the live figure can be recoloured from the
//     club's kit; the painter has no CSS, and the fallback IS the colour the JS
//     shows before a kit is applied, so nothing is invented. Recolouring is
//     done at draw time instead — see `manager_art.dart`.
//   * `currentColor` becomes the skin tone, for the same reason.
//
// HAIR COMES IN TWO LAYERS. A style is either one string or `{back, front}`:
// the mass behind the skull and the part that falls over it. They are kept
// apart because the head is drawn BETWEEN them, and flattening the two would
// put a mohawk's fin behind the face.
//
//   node tool/gen_manager_art.mjs

import { writeFileSync } from 'node:fs';

const av = await import('../../merge-empire-fc/src/data/managerAvatar.js');

// The figure's own space. Every fragment is drawn against it, which is what
// keeps a hat on the head without any nudging.
const VIEWBOX = '0 0 120 170';

// The defaults the fragments already carry. Listed rather than scraped from
// each `var()` so a fragment that forgot its fallback fails loudly here rather
// than generating an unpainted shape.
const VARS = {
  '--hair': '#3a2a1c',
  '--kit': '#4caf50',
  '--kit-dark': '#2e6b30',
  '--kit-light': '#6fbf73',
  '--trim': '#2e6b30',
  '--skin': '#e8b48c',
  '--skin-shade': '#c9946f',
  '--coat': '#2f3a4a',
  '--suit': '#26303d',
  '--shirt': '#f2f2f2',
};

const resolveVars = (markup) =>
  String(markup).replace(
    /var\(\s*(--[a-z-]+)\s*(?:,\s*([^)]+))?\)/gi,
    (_, name, fallback) => {
      const value = (fallback ?? '').trim() || VARS[name];
      if (!value) throw new Error(`no fallback and no default for ${name}`);
      return value;
    },
  );

/** One fragment, wrapped so the painter can read it on its own. */
const wrap = (markup) => {
  const body = resolveVars(markup).replace(/currentColor/g, VARS['--skin']);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEWBOX}">${body}</svg>`;
};

const lit = (s) =>
  "'''" + String(s).replace(/\\/g, '\\\\').replace(/\$/g, '\\$') + "'''";

/** A style is one string, or a back/front pair. Normalised to the pair. */
const layers = (value) =>
  typeof value === 'string'
    ? { back: '', front: value }
    : { back: value.back ?? '', front: value.front ?? '' };

const lines = [
  '// GENERATED by tool/gen_manager_art.mjs — do not edit.',
  '// Source: ../merge-empire-fc/src/data/managerAvatar.js',
  '',
  "/// The manager avatar's parts, as the SVG fragments the JS composes.",
  '///',
  '/// Every part is drawn in the same `0 0 120 170` space, so a hat lands on the',
  '/// head with no positioning of its own. Drawn by',
  '/// `ui/widgets/svg_canvas.dart`; recoloured at draw time by',
  '/// `data/manager_art.dart`, which is also where the layering is explained.',
  'library;',
  '',
  '/// The space every part is drawn in.',
  'const double managerArtWidth = 120;',
  'const double managerArtHeight = 170;',
  '',
  '/// Hair, as the mass BEHIND the skull and the part that falls over it. The',
  '/// head is drawn between the two.',
  'const Map<String, (String back, String front)> managerHair = {',
];

for (const [id, value] of Object.entries(av.HAIR_STYLES)) {
  const { back, front } = layers(value);
  lines.push(`  '${id}': (`);
  lines.push(`    ${back ? lit(wrap(back)) : "''"},`);
  lines.push(`    ${front ? lit(wrap(front)) : "''"},`);
  lines.push('  ),');
}
lines.push('};', '');

const flatTables = {
  managerBeards: ['FACIAL_HAIR', "Facial hair, over the jaw."],
  managerHats: ['HATS', 'Headwear, over everything on the head.'],
  managerOutfits: [
    'OUTFIT_OVERLAYS',
    'What he is wearing, over the torso. Most of the tracksuit is palette rather'
      + ' than shape, so several of these are a collar line and nothing else.',
  ],
  managerNeck: [
    'NECK_ITEMS',
    'Round the throat — drawn UNDER the head and OVER the torso, which is why it'
      + ' is its own slot rather than part of the outfit.',
  ],
};

for (const [name, [source, doc]] of Object.entries(flatTables)) {
  lines.push(`/// ${doc}`);
  lines.push(`const Map<String, String> ${name} = {`);
  for (const [id, markup] of Object.entries(av[source])) {
    lines.push(`  '${id}': ${markup ? lit(wrap(markup)) : "''"},`);
  }
  lines.push('};', '');
}

writeFileSync('lib/data/manager_art.g.dart', lines.join('\n'), 'utf8');

const count = Object.keys(av.HAIR_STYLES).length
  + Object.keys(av.FACIAL_HAIR).length
  + Object.keys(av.HATS).length
  + Object.keys(av.OUTFIT_OVERLAYS).length
  + Object.keys(av.NECK_ITEMS).length;
console.log(`wrote lib/data/manager_art.g.dart — ${count} parts`);
