// Captures the club artwork as data.
//
// `assets/clubArt.js` is a table of SVG STRINGS built from primitives — 116
// rects, 24 circles, 11 ellipses and fifteen simple quadratics. Rather than
// transcribe thirty-six scenes into Dart by eye, the strings come across
// verbatim and a small painter draws them. That makes this the same kind of
// port as the i18n catalogues: generated data, not hand-written code.
//
//   node tool/gen_club_art.mjs

import { writeFileSync } from 'node:fs';

const art = await import('../../merge-empire-fc/src/assets/clubArt.js');

const CATEGORIES = ['TRAINING', 'MERCH', 'STADIUM', 'MEDIA', 'SPONSOR', 'FANZONE'];
const MAX_TIER = 6;

const lit = (s) =>
  "'''" + String(s).replace(/\\/g, '\\\\').replace(/\$/g, '\\$') + "'''";

const lines = [
  '// GENERATED by tool/gen_club_art.mjs — do not edit.',
  '// Source: ../merge-empire-fc/src/assets/clubArt.js',
  '',
  '/// The club artwork, as the SVG the JS builds.',
  '///',
  '/// Kept as source strings and drawn by `ui/widgets/svg_canvas.dart`, because',
  '/// the JS composes them from primitives rather than shipping files. Every',
  '/// element in here is a rect, circle, ellipse, polygon, line, text or a path',
  '/// of simple quadratics — no dependency needed to draw any of it.',
  'library;',
  '',
  'const Map<String, List<String>> clubArtByCategory = {',
];

for (const category of CATEGORIES) {
  lines.push(`  '${category}': [`);
  for (let tier = 1; tier <= MAX_TIER; tier++) {
    lines.push(`    ${lit(art.getClubAssetSvg(category, tier))},`);
  }
  lines.push('  ],');
}
lines.push('};');
lines.push('');
lines.push('/// The Club screen hero, one per stadium tier.');
lines.push('const List<String> stadiumBackgrounds = [');
for (let tier = 1; tier <= MAX_TIER; tier++) {
  lines.push(`  ${lit(art.getStadiumBackgroundSvg(tier))},`);
}
lines.push('];');
lines.push('');
lines.push('/// Artwork for [category] at [tier], clamped to what exists.');
lines.push('String clubArtFor(String category, int tier) {');
lines.push("  final art = clubArtByCategory[category] ?? clubArtByCategory['TRAINING']!;");
lines.push('  final idx = (tier - 1).clamp(0, art.length - 1);');
lines.push('  return art[idx];');
lines.push('}');

writeFileSync('lib/data/club_art.g.dart', lines.join('\n') + '\n');
process.stdout.write(`wrote ${CATEGORIES.length} categories x ${MAX_TIER} tiers\n`);
