// Converts the ten JS catalogs to generated Dart maps.
//
// Dart rather than ARB: 30 keys are not valid identifiers (a nation name with a
// space or a diacritic), and the engines look keys up at runtime from strings,
// which gen_l10n cannot do at all. See the i18n design spec.
//
// Run from the repo root — the read path is relative to this file, the write
// path to the working directory:
//
//   node tool/gen_i18n.mjs

import { writeFileSync, mkdirSync } from 'node:fs';

const IDS = ['en', 'es', 'pt', 'fr', 'de', 'it', 'ja', 'ko', 'zh', 'ar'];
const SRC = '../../merge-empire-fc/src/i18n/locales/';
const OUT = 'lib/i18n/locales/';

const HEADER = (id) => `// GENERATED by tool/gen_i18n.mjs — do not edit.
// Source: ../merge-empire-fc/src/i18n/locales/${id}.js
`;

// Dart single-quoted string literal. $ opens an interpolation in Dart and a
// backslash escapes, so both are escaped even though no value carries one today.
const lit = (s) =>
  "'" +
  String(s)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n') +
  "'";

mkdirSync(OUT, { recursive: true });

const loaded = {};
for (const id of IDS) {
  loaded[id] = (await import(SRC + id + '.js')).default;
}

const enKeys = Object.keys(loaded.en);

for (const id of IDS) {
  const cat = loaded[id];
  const keys = Object.keys(cat);

  // A duplicate would be a compile error in a const Dart map, but the error
  // would name a line rather than the catalog that produced it.
  const seen = new Set();
  for (const k of keys) {
    if (seen.has(k)) throw new Error(`${id}: duplicate key ${k}`);
    seen.add(k);
  }
  for (const k of keys) {
    if (typeof cat[k] !== 'string') throw new Error(`${id}: ${k} is not a string`);
  }
  if (id !== 'en') {
    const missing = enKeys.filter((k) => !(k in cat));
    const extra = keys.filter((k) => !(k in loaded.en));
    if (missing.length || extra.length) {
      throw new Error(
        `${id}: key drift — missing ${missing.length}, extra ${extra.length}`,
      );
    }
  }

  const body = keys.map((k) => `  ${lit(k)}: ${lit(cat[k])},`).join('\n');
  writeFileSync(
    `${OUT}${id}.g.dart`,
    `${HEADER(id)}\n// ignore_for_file: lines_longer_than_80_chars\nlibrary;\n\n` +
      `const Map<String, String> ${id}Catalog = <String, String>{\n${body}\n};\n`,
  );
}

const imports = IDS.map(
  (id) => `import 'package:merge_empire_fc/i18n/locales/${id}.g.dart';`,
).join('\n');
const entries = IDS.map((id) => `  '${id}': ${id}Catalog,`).join('\n');
writeFileSync(
  'lib/i18n/catalogs.g.dart',
  `// GENERATED by tool/gen_i18n.mjs — do not edit.\n\n${imports}\n\n` +
    `const Map<String, Map<String, String>> catalogs =\n    <String, Map<String, String>>{\n${entries}\n};\n`,
);

process.stdout.write(`wrote ${IDS.length} catalogs, ${enKeys.length} keys each\n`);
