// GENERATED by tool/gen_i18n.mjs — do not edit.

import 'package:merge_empire_fc/i18n/locales/en.g.dart';
import 'package:merge_empire_fc/i18n/locales/es.g.dart';
import 'package:merge_empire_fc/i18n/locales/pt.g.dart';
import 'package:merge_empire_fc/i18n/locales/fr.g.dart';
import 'package:merge_empire_fc/i18n/locales/de.g.dart';
import 'package:merge_empire_fc/i18n/locales/it.g.dart';
import 'package:merge_empire_fc/i18n/locales/ja.g.dart';
import 'package:merge_empire_fc/i18n/locales/ko.g.dart';
import 'package:merge_empire_fc/i18n/locales/zh.g.dart';
import 'package:merge_empire_fc/i18n/locales/ar.g.dart';

const Map<String, Map<String, String>> catalogs =
    <String, Map<String, String>>{
  'en': enCatalog,
  'es': esCatalog,
  'pt': ptCatalog,
  'fr': frCatalog,
  'de': deCatalog,
  'it': itCatalog,
  'ja': jaCatalog,
  'ko': koCatalog,
  'zh': zhCatalog,
  'ar': arCatalog,
};
