/// **ENGLISH COPY THIS REPO OWNS, and the reason it exists is that the JS is
/// going away.**
///
/// Every string in `lib/i18n/locales/*.g.dart` was generated by
/// `tool/gen_i18n.mjs` out of `../merge-empire-fc/src/i18n/locales/*.js`. That
/// repo is being retired, which takes the generator with it — so the rule that
/// "no new `t()` key can be added from here" would have become permanent, and
/// widening a commentary pool would have meant editing a file whose header says
/// it is generated and whose source no longer exists.
///
/// This is the way round it. Nothing generated is edited by hand; this map is
/// laid OVER the generated English at load, in `i18n.dart`. Adding copy is
/// editing this file and nothing else — no node, no sibling checkout.
///
/// **HOT RESTART, NOT HOT RELOAD, after editing this.** `englishCatalog` is a
/// lazily-initialised top-level `final`, so the merge runs once on the first
/// lookup and hot reload keeps the value it already computed — a key added
/// here goes on rendering as its own key (`report.opp.shut_us_out` on screen)
/// until the process starts again. Reported from the couch, and it is worth
/// knowing about rather than designing away: a getter that re-merged per call
/// would put a map rebuild inside `t()`, which is called from build methods.
///
/// **Two maps, because the two jobs are different.**
///
/// - [enMore] APPENDS lines to a pool that already exists. Dozens of catalogue
///   entries are `|`-separated pools that `tPool`, `tPoolStable` and
///   `tPoolUnused` draw one line from, and widening one is by far the commonest
///   thing anybody wants to do here. Restating the whole pool to add a sentence
///   to it would duplicate the generated copy and go stale the moment either
///   half moved, so this holds only the NEW lines.
/// - [enCopy] REPLACES a key outright, and is where a brand-new key goes.
///
/// **English only, deliberately.** The other nine catalogues are translations
/// and nothing here can write them. A key only this file carries resolves in
/// every locale through `t()`'s existing English fallback, which is the same
/// path a missing translation already takes; a POOL widened here stays the
/// generated width in French, which is correct — appending English sentences to
/// a French pool would put English on a French screen.
library;

/// Extra lines for pools that already exist. See the header.
///
/// The key must already be in the generated English or the line is the whole
/// pool, which is legal and is probably a mistake — `en_copy_test.dart` says so.
/// Values are `|`-separated exactly like the catalogue's own.
///
/// **Mind the placeholders.** A pool's variants do not all have to use the same
/// ones, but every variant may only use placeholders the CALL SITE passes —
/// `report.clean_sheet` shipped a variant naming `{opp}` when the caller passed
/// only `{club}`, and one write-up in three printed the brace at the player.
const Map<String, String> enMore = <String, String>{
  // ── The commentary feed ──────────────────────────────────────────────────
  //
  // Atmosphere lines take NO placeholders: `feedOf` passes none for the flow
  // pools. See `match_clock.dart`.
  'commentary.flow.open.0':
      'The referee checks the watch, and we are away.|'
      'Under way, and the first ball is put straight into the channel.',
  'commentary.flow.open.1':
      'A cagey opening, both sides feeling for a weakness.|'
      'The first real spell of pressure, and it is not being cleared properly.',
  'commentary.flow.open.2':
      'Both ends of the ground are in good voice already.|'
      'Somebody has started a song behind the goal.',
  'commentary.flow.firstA.0':
      'The tempo has picked up, and with it the quality.|'
      'A patient spell, working the ball from side to side.',
  'commentary.flow.firstA.1':
      'A shot from the angle, and it flashes across the six-yard box.|'
      'Turned goalwards from close range and blocked at the last.',
  'commentary.flow.firstA.2':
      'The overlap is on every time they go down that side.|'
      'A clever ball inside the full-back, and the cross is cut out.',
  'commentary.flow.firstA.3':
      'Another corner, and the keeper comes for this one too.|'
      'A set piece headed clear as far as the edge, and volleyed miles over.',
  'commentary.flow.firstB.0':
      'A free kick worth having, and there are three of them standing over it.|'
      'The wall is walked back ten yards, and the referee has a word about it.',
  'commentary.flow.firstB.1':
      'A save at full stretch, and the corner comes to nothing.|'
      'Tipped over, and the ground rises to the keeper.',
  'commentary.flow.firstB.3':
      'Blocked on the line, and the follow-up is blocked as well.|'
      'A goal-line clearance, and the defender takes it in the face for the trouble.',
  'commentary.flow.secondA.0':
      'Straight back on the front foot after the interval.|'
      'The second half begins the way the first one ended.',
  'commentary.flow.secondA.1':
      'The switch has given them an extra man in midfield, and it shows.|'
      'Whatever was changed at the break is working.',
  'commentary.flow.secondA.2':
      'Both boxes are being visited now, and neither defence looks settled.|'
      'This has turned into a proper game in the last ten minutes.',
  'commentary.flow.secondA.3':
      'Play stops while a head knock is checked.|'
      'The physio is on again, and there is a stretcher warming up.',
  'commentary.flow.secondB.0':
      'Neither midfield will give an inch here.|'
      'Every second ball is being contested twice.',
  'commentary.flow.secondB.1':
      'A dipping effort from range that the keeper does well to hold.|'
      'Struck from distance, and it skids up off the turf into the keeper.',
  'commentary.flow.secondB.2':
      'Worked through the eye of a needle, and cleared off the toe.|'
      'A backheel in the area nearly opens it up, and the last man reads it.',
  'commentary.flow.closing.0':
      'The last ten, and the game has stretched.|'
      'Into the closing stages with everything still to play for.',
  'commentary.flow.closing.1':
      'Every second ball matters now.|'
      'It has become a game of tackles and headers.',
  'commentary.flow.closing.2':
      'They are defending the edge of their own box now.|'
      'The clock is the only friend one of these sides has.',
  'commentary.flow.closing.3':
      'Everything is being launched forward now.|'
      'The keeper has come up for this one.',
  'commentary.flow.closing.4':
      'You can hear the tension in here.|'
      'Nobody in this ground is sitting down.',
  'commentary.flow.addedtime.0':
      'Anything can happen in these last few seconds.|'
      'The board is up and the ground has found its voice again.',
  'commentary.flow.addedtime.1':
      'Seeing it out, and every touch is being cheered.|'
      'Time-wasting now, and nobody on that bench minds a bit.',
  'commentary.flow.addedtime.2':
      'Four minutes signalled, and one bench is furious about it.|'
      'The added minutes go up, and there is a groan from three sides of the ground.',
  'commentary.flow.addedtime.3':
      'One more ball into the box and that will be that.|'
      'There is time for one more attack, and they know it.',

  // Goals. `{us}` is our club, `{scorer}` the player who scored.
  'commentary.goal.equalise.with_scorer':
      '{scorer} hauls {us} level!|'
      'Level again, and {scorer} is the one who did it!|'
      '{scorer} finishes it off — {us} are back on terms!',
  'commentary.goal.equalise.no_scorer':
      '{us} are level again!|'
      'All square — {us} have found it!|'
      '{us} answer back!',
  'commentary.goal.extend.with_scorer':
      '{scorer} again, and {us} are out of sight!|'
      'No way back now — {scorer} makes it another for {us}!|'
      '{scorer} strikes again, and {us} keep going!',
  'commentary.goal.extend.no_scorer':
      '{us} are not finished yet!|'
      'Another one for {us}, and this is becoming a rout!|'
      '{us} keep pouring forward!',
  'commentary.goal.lead.with_scorer':
      '{scorer} does it — {us} lead!|'
      'The opener, and it belongs to {scorer}! {us} in front!|'
      '{scorer} finds the bottom corner and {us} are ahead!',
  'commentary.goal.lead.no_scorer':
      '{us} are ahead!|'
      'The opener goes to {us}!|'
      '{us} strike first!',
  'commentary.goal.pullback.with_scorer':
      '{scorer} keeps {us} alive!|'
      'A goal back for {us}, and {scorer} claims it!|'
      '{scorer} gives {us} a chance!',
  'commentary.goal.pullback.no_scorer':
      '{us} get one back and there is life in this!|'
      'A consolation, or the start of something? {us} score!|'
      '{us} are not done!',
  'commentary.opp_goal':
      '{them} carve it open and finish without breaking stride.|'
      'A ball over the top, and {them} are in behind again.|'
      'Nobody closes the shot down, and {them} make it count.|'
      '{them} win the second ball on the edge and bury it.',

  // Chances. `{who}` is whichever club had it.
  'commentary.forces_save':
      '{who} force a fine save low to the near post.|'
      'A near-post flick from a {who} corner needs a strong hand.|'
      '{who} get in behind and the keeper spreads well to block it.',
  'commentary.hit_post':
      '{who} clip the outside of the post from a tight angle.|'
      'The bar comes to the rescue with {who} celebrating already.|'
      'It is off the post, off the keeper, and somehow not in for {who}.',
  'commentary.shot_over':
      '{who} lash at it and put it well over.|'
      'A glorious chance for {who}, and it clears the stand.|'
      '{who} take the shot early and get right underneath it.',
  'commentary.shot_wide':
      '{who} lean back and drag it past the far post.|'
      'Half a yard of space for {who}, and it goes wide of the near post.|'
      'A {who} header from the corner drifts the wrong side.',
  'commentary.blocked':
      'A {who} shot deflected behind by a desperate leg.|'
      '{who} shoot from the edge and it cannons off a defender.|'
      'Two {who} efforts in a row, both charged down.',
  'commentary.dispossessed':
      '{who} lose it to a tackle that wins the ball cleanly.|'
      'A {who} attack ends with a poor touch in a good area.|'
      '{who} are closed down and robbed on the edge of the box.',

  // The referee's pocket. `{player}`, `{us}` and `{opp}` are all passed.
  'commentary.booking.yellow':
      'A shirt-pull from {player} stops the counter, and it is a booking.|'
      '{player} catches an ankle and the referee reaches for the yellow.',
  'commentary.booking.opp_yellow':
      'A {opp} defender goes into the book for a professional foul.|'
      'That is a caution for {opp}, and it was coming.',

  // ── His word at the whistle ──────────────────────────────────────────────
  //
  // `{us}` and `{them}` are the GOALS, `{opp}` is the club. First person: this
  // is Colin talking to you about your own team, not the commentary.
  'commentary.thriller_win':
      '{us}-{them}. My heart cannot take many of those, but what a win.|'
      'We found a way, {us}-{them}. That is what good sides do against {opp}.',
  'commentary.thriller_draw':
      '{us}-{them}. Both of us gave everything and neither deserved to lose.|'
      'A point from a cracker against {opp}, {us}-{them}. On we go.',
  'commentary.thriller_loss':
      '{us}-{them}. We were the better side for long spells and have nothing for it.|'
      'Beaten {us}-{them} in a game we could have won twice over.',
  'commentary.demolition':
      '{us}-{them}. Everything clicked today and {opp} could not live with it.|'
      'That is a statement, {us}-{them}. Enjoy the bus home.',
  'commentary.drubbing':
      '{us}-{them}. We were off it from the first whistle and {opp} punished us.|'
      'Chalk {us}-{them} off and move on. There is nothing to learn from a day like that except to forget it.',
  'commentary.high_scoring_win':
      '{us}-{them}. Thrilling, terrifying, and three points against {opp}.|'
      'We outscored {opp} rather than outplayed them, {us}-{them}. It counts the same.',
  'commentary.high_scoring_loss':
      '{us}-{them} at {opp}. We can score against anybody and we can concede to anybody too.|'
      'Six goals and we come away with nothing. {us}-{them}.',
  'commentary.nervy_one_nil':
      'One goal, a clean sheet, and three points off {opp}. Do not overthink it.|'
      'A 1-0 that felt like a 4-3. We will take the points and the clean sheet.',
  'commentary.nil_nil':
      'Nothing at either end against {opp}. Some weeks you just bank the point.|'
      '0-0. Not one to show the grandchildren, but we are not beaten.',

  // ── The full-time write-up ───────────────────────────────────────────────
  //
  // Third person throughout — this is an independent account naming both clubs,
  // so no variant here may say "we". The HEADLINE pools are not widened here:
  // the generated ones open on the score, and they are replaced whole in
  // [enCopy] instead — see "IT OPENS LIKE THE WHISTLE HAS JUST GONE".
  'report.shape.turnaround':
      'Behind, then in front — {club} turned this one around.|'
      '{club} lost the first goal and won everything after it.',
  'report.shape.chasing':
      '{club} were playing catch-up from the moment {opp} scored.|'
      'The first goal shaped it, and it was not {club}\'s.',
  'report.shape.never_behind':
      '{club} were in front from their first goal and stayed there.|'
      'Not once did {opp} lead. {club} set the terms and kept them.',
  'report.shape.threw_it':
      '{club} led this and finished it level, which is a point dropped rather than won.|'
      'A lead let slip by {club}, and {opp} will feel they earned the comeback.',
  'report.scorers.one':
      'One goal, and {player} scored it for {club}.|'
      '{player} settled it for {club}.',
  'report.scorers.brace':
      'Two for {player}, who gave {club}\'s attack its shape all afternoon.|'
      '{player} scored a pair and could have had a third.',
  'report.scorers.hat_trick':
      '{player} took {n} of them home, and the match ball with it.|'
      'A {n}-goal afternoon for {player}, which is what {club} will remember of this one.',
  'report.clean_sheet':
      'And nothing conceded — {club}\'s back line were not troubled for long.|'
      'A clean sheet for {club} to go with the result.',
  'report.next.home':
      '{club} welcome {opp} to their own ground next.|'
      'It is {opp} at home for {club} in the next round.',
  'report.next.away':
      '{club} have a trip to {opp} to come.|'
      'Next for {club}: away at {opp}.',
};

/// Whole keys — a replacement for a generated one, or a key the catalogues
/// never had. See the header.
///
/// Empty is the normal state: [enMore] covers widening a pool, which is what
/// this repo mostly wants. Reach for this one when the JS's own wording is
/// wrong for the port, or when a screen needs a string the catalogues do not
/// carry at all.
const Map<String, String> enCopy = <String, String>{

  // ── "1 points" ───────────────────────────────────────────────────────────
  //
  // The table beat hardcoded the word, so a side on a single point was told it
  // had "1 points". Reported from the couch. English's plural suffix already
  // travels as `{s}` for `place{s}`; points needed one of its own, so the
  // engine passes `{ps}` and these are the same five variants with
  // `point{ps}` in place of `points`.
  //
  // **Overridden here rather than in the generated file**, which is the whole
  // reason `enCopy` exists: the catalogues come out of a JS repo that is being
  // retired. The other nine locales keep their own wording and simply ignore
  // the spare parameter, which is what `t()` already does with the 57 entries
  // that drop English's `{s}`.
  'report.table.climbed':
      'The win moves {club} up {n} place{s} to {pos} in the table, on {pts} point{ps}.|'
      '{club} climb {n} place{s} to {pos} as a result, with {pts} point{ps} from the season so far.|'
      'That result lifts {club} to {pos}, {n} place{s} higher than before it, on {pts} point{ps}.|'
      '{club} move {n} place{s} higher to {pos}, now on {pts} point{ps}.|'
      'The three points take {club} to {pos} in the table, {n} place{s} up, on {pts} point{ps}.',
  'report.table.dropped':
      'The result drops {club} {n} place{s} to {pos}, on {pts} point{ps}.|'
      '{club} fall {n} place{s} to {pos} in the table, with {pts} point{ps}.|'
      'That leaves {club} {pos} and falling, {n} place{s} worse off, on {pts} point{ps}.|'
      '{club} slip {n} place{s} to {pos} on {pts} point{ps}.|'
      'That result costs {club} {n} place{s} and leaves them {pos} with {pts} point{ps}.',
  'report.table.held':
      '{club} stay {pos} in the table, now on {pts} point{ps}.|'
      'The result leaves {club} where they were, {pos} on {pts} point{ps}.|'
      'No change in the table for {club}, who remain {pos} with {pts} point{ps}.|'
      '{club} hold their place at {pos}, on {pts} point{ps}.|'
      'Nothing moves for {club}, still {pos} and now on {pts} point{ps}.',
  // ── HOW THE OPPOSITION PLAYED ────────────────────────────────────────────
  //
  // **The first keys this repo has ever owned outright**, and the reason is
  // that the write-up only ever described one of the two teams in it. The
  // shape, the scorers, the cards, the tactical switch and the table are all
  // facts about the player's club, so a beaten side got several sentences on
  // how poorly it had played and the winners were named in a scoreline.
  // Reported from the couch: an independent summary written for supporters of
  // both clubs has to say how the other lot played.
  //
  // Voice: somebody who watched the match and is telling you about it. Not a
  // scorecard, not a press release — no "clinical finishing" or "the three
  // points were vital", and never "we". `{club}` and `{opp}` are the two
  // clubs, and nothing else is passed. See `buildMatchReport`.
  //
  // They won it from a losing position.
  'report.opp.comeback':
      '{opp} looked beaten and never played like it, and by the end they were '
          'the side you would have put your money on.|'
      'Credit to {opp} — they were second best for a spell and turned the '
          'afternoon on its head.|'
      'It says something about {opp} that being behind seemed to settle them.',
  // Three clear or better: a performance rather than a result.
  'report.opp.rampant':
      '{opp} were outstanding, quick in everything they did and merciless with '
          'every mistake that came along.|'
      'This was {opp} at their very best, and anyone who was there for them '
          'will be talking about it all week.|'
      'Everything {opp} tried came off. Not many sides would have lived with '
          'them today.',
  // A win and a clean sheet — two jobs done, and the copy should say so.
  'report.opp.shut_us_out':
      '{opp} were as good without the ball as with it, and {club} never found a '
          'way past them.|'
      'A clean sheet and the points for {opp}, who defended their box properly '
          'from the first minute to the last.|'
      '{opp} gave {club} nothing to work with, which is as much why they won as '
          'anything they did at the other end.',
  // A one or two-goal win with goals at both ends.
  'report.opp.clinical':
      'There was not a great deal between these two; {opp} were simply sharper '
          'when the chances came.|'
      '{opp} took their moments and {club} did not, which is usually the whole '
          'of it.|'
      '{opp} did not have to be the better side to win this, and they were not '
          'far off it anyway.',
  // We led and did not win: they earned the point back.
  'report.opp.fought_back':
      '{opp} were behind and kept coming, and few in the ground would call the '
          'point undeserved.|'
      'It took some character from {opp} to get back into this one.|'
      '{opp} refused to accept it and earned their share of the afternoon the '
          'hard way.',
  'report.opp.stalemate':
      '{opp} were every bit as organised as {club}, and neither side could find '
          'the gap.|'
      'Little to choose between them — {opp} were as hard to break down as '
          '{club} were.|'
      '{opp} came for a point and defended like a side that meant it.',
  'report.opp.matched':
      '{opp} matched {club} for long spells and will feel much the same about '
          'the result.|'
      'Honest, even stuff from {opp}, who were never behind and never quite in '
          'front.|'
      'There was little between them, and {opp} will not feel they lost '
          'anything here.',
  // We won by three or more.
  'report.opp.outclassed':
      'It was a long afternoon for {opp}, second to most things and never able '
          'to get a foothold in it.|'
      '{opp} will want this one forgotten quickly. Very little went right for '
          'them.|'
      'Not much worked for {opp}, and the gap between the two sides was plain '
          'well before the end.',
  // We won by one or two.
  'report.opp.pushed':
      '{opp} made {club} work for it and were not far away themselves.|'
      '{opp} will feel they had enough of this game to take something from it.|'
      'There was more in this for {opp} than the scoreline gives them.',

  // ── THE SUMMARY USES EVERYTHING ──────────────────────────────────────────
  //
  // Reported from the couch against a 1-0 won in the 88th minute: "held on to
  // a single goal for longer than was comfortable", about a lead two minutes
  // old. The direction that came with it: a life-like summary that uses the
  // stats, the tactics, the goals and who scored them and when, the
  // substitutions and the discipline. These are the sentences that tell them.
  // Third person throughout, both clubs named, nothing says "we". `{minute}`
  // arrives as an ordinal ("88th") from `ordinalOf`; `{score}` is written home
  // team first like the headline's.

  // ── IT OPENS LIKE THE WHISTLE HAS JUST GONE ──────────────────────────────
  //
  // Reported from the couch: the first line "just gives the score (which is
  // already visible) and gives a one liner", where it should open like "the
  // whistle has gone and there was one goal in it" or "what a thriller of a
  // game, 7 goals between them but it goes to {team}". The generated headline
  // pools all lead with `{score}`, so the fourteen are REPLACED here rather than
  // widened, and three thriller pools are added for a high-scoring one-goal
  // result and a 3-3. The scoreboard above the card has the score;
  // the opener has the moment. `{ours}` and `{theirs}` are our goals and theirs,
  // `{total}` is both together.
  'report.win.rout':
      'It\'s all over, and it was a rout: {club} put {ours} past {opp} and '
          'barely broke sweat doing it.|'
      'The whistle has gone on a demolition. {ours} for {club}, {theirs} for '
          '{opp}, and the margin flatters nobody but the winners.|'
      'Full time, and {club} have taken {opp} apart — {ours} goals, and it '
          'could have been more.',
  'report.win.comfortable':
      'The whistle has gone, and {club} have won this at a canter, three goals '
          'clear of {opp}.|'
      'It\'s all over. Three goals in it at the end, and {club} were never in '
          'any danger of giving them back.|'
      'Full time. {club} beat {opp} by three and did the job without ever '
          'having to force it.',
  'report.win.clear':
      'The whistle has gone, and {club} have won it by two. {opp} had spells '
          'without ever looking like getting level.|'
      'It\'s all over, two goals in it, and {club} have managed the afternoon '
          'from the moment the second went in.|'
      'Full time, and a two-goal win for {club} that was about as comfortable '
          'as it sounds.',
  'report.win.narrow':
      'The whistle has gone, and there was one goal in it — and it was '
          '{club}\'s.|'
      'It\'s all over. A single goal separates them at the end, and {club} have '
          'the points.|'
      'Full time, and {club} have edged it. One goal in it, and it could have '
          'gone either way.',
  'report.win.late':
      'The whistle has gone, and {club} have won it late — the goal that '
          'settled it came in the {minute} minute.|'
      'It\'s all over, and what a finish: level until the {minute} minute, and '
          'then {club} found the one that {opp} had no time to answer.|'
      'Full time. A point had looked the likeliest result until the {minute} '
          'minute, when {club} won it.',
  'report.win.thriller':
      'It\'s all over, and what a thriller — {total} goals between them, and it '
          'goes to {club}.|'
      'The whistle has gone on a {total}-goal thriller, and {club} have come out '
          'of it with the points.|'
      'Full time, and breathe. {total} goals, and it went {club}\'s way by the '
          'odd one.',
  'report.draw.goalless':
      'The whistle has gone, and nothing to separate them — no goals, and not '
          'many chances either.|'
      'It\'s all over, goalless. The two goalkeepers had a quiet afternoon of '
          'it.|'
      'Full time, and honours even with nothing on the scoreboard.',
  'report.draw.shared':
      'The whistle has gone on a draw — {ours} apiece, and neither {club} nor '
          '{opp} could find the one that settled it.|'
      'It\'s all over, and they share the points. {ours} each, in a match that '
          'had a winner in it somewhere.|'
      'Full time, and level. Neither dressing room will be entirely happy with '
          'that.',
  'report.draw.late':
      'The whistle has gone on a draw, and the equaliser did not arrive until '
          'the {minute} minute — a point won for one side and two dropped for '
          'the other.|'
      'It\'s all over, level, and it took until the {minute} minute to get '
          'there.|'
      'Full time, with the goal that levelled it coming in the {minute} minute.',
  'report.draw.thriller':
      'It\'s all over, and what a game — {total} goals and nothing to separate '
          'them.|'
      'The whistle has gone on a {total}-goal thriller that neither side could '
          'win.|'
      'Full time, and a point each after {total} goals between them.',
  'report.loss.narrow':
      'The whistle has gone, and there was one goal in it — and it was '
          '{opp}\'s.|'
      'It\'s all over. {opp} take it by a single goal, and {club} take the '
          'questions.|'
      'Full time, and {club} have lost by the odd goal. Fine margins, and they '
          'went {opp}\'s way.',
  'report.loss.late':
      'The whistle has gone, and {club} have lost it late — {opp}\'s winner '
          'came in the {minute} minute.|'
      'It\'s all over, and a cruel finish: level until the {minute} minute, and '
          'then {opp} scored the one that mattered.|'
      'Full time. {club} had done enough for a point until the {minute} minute, '
          'and not a minute longer.',
  'report.loss.thriller':
      'It\'s all over, and what a thriller — {total} goals between them, but it '
          'goes to {opp}.|'
      'The whistle has gone on a {total}-goal thriller, and {club} have come out '
          'of it with nothing.|'
      'Full time, and breathe. {total} goals, and it went {opp}\'s way by the '
          'odd one.',
  'report.loss.clear':
      'The whistle has gone, and {opp} have won it by two. {club} were second '
          'best in both boxes.|'
      'It\'s all over, two goals in it, and {club} never quite got back into it '
          'after the second.|'
      'Full time, and a two-goal defeat for {club} against an {opp} side sharper '
          'where it mattered.',
  'report.loss.comfortable':
      'The whistle has gone, and {club} have been well beaten — three goals '
          'clear to {opp} at the end.|'
      'It\'s all over. Three in it, and {club} were containing it long before '
          'the whistle.|'
      'Full time, and a chastening afternoon for {club}, beaten by three.',
  'report.loss.rout':
      'It\'s all over, and it was a hiding: {opp} put {theirs} past {club}.|'
      'The whistle has gone on a rout. {theirs} for {opp}, {ours} for {club}, '
          'and no complaints from anyone.|'
      'Full time, and {club} have been taken apart — {theirs} conceded, and it '
          'could have been more.',

  // Every goal, keyed by what it did to the match. Theirs carry the club,
  // because the sim does not name their scorers.
  'report.goal.ours.opener':
      '{scorer} opened the scoring for {club} in the {minute} minute.|'
      'The first goal came in the {minute} minute, {scorer} putting {club} '
          'ahead.',
  'report.goal.ours.leveller':
      '{scorer} levelled it for {club} in the {minute} minute, {score}.|'
      '{club} were back level in the {minute} minute through {scorer}.',
  'report.goal.ours.lead':
      '{scorer} put {club} in front in the {minute} minute, {score}.|'
      'In the {minute} minute {scorer} scored to put {club} ahead at {score}.',
  'report.goal.ours.extend':
      '{scorer} made it {score} in the {minute} minute.|'
      '{club} stretched it to {score} in the {minute} minute, {scorer} with '
          'the goal.',
  'report.goal.ours.pull_back':
      '{scorer} pulled one back for {club} in the {minute} minute, {score}.|'
      '{club} got one back in the {minute} minute through {scorer}, {score}.',
  'report.goal.theirs.opener':
      '{opp} opened the scoring in the {minute} minute.|'
      'The first goal was {opp}\'s, in the {minute} minute.',
  'report.goal.theirs.leveller':
      '{opp} levelled in the {minute} minute, {score}.|'
      '{opp} drew level in the {minute} minute.',
  'report.goal.theirs.lead':
      '{opp} went in front in the {minute} minute, {score}.|'
      'In the {minute} minute {opp} scored to lead {score}.',
  'report.goal.theirs.extend':
      '{opp} made it {score} in the {minute} minute.|'
      '{opp} added another in the {minute} minute, {score}.',
  'report.goal.theirs.pull_back':
      '{opp} pulled one back in the {minute} minute, {score}.|'
      '{opp} got one back in the {minute} minute, {score}.',

  // The board at the whistle, our side first.
  'report.stats.board':
      '{club} had {poss}% of the ball and {shots} shots to {opp}\'s {oppShots}, '
          '{onTarget} of them on target.|'
      'The numbers: {poss}% possession to {club}, {shots} shots against '
          '{oppShots}, and {corners} corners to {oppCorners}.|'
      '{club} finished with {shots} shots, {onTarget} on target, against '
          '{oppShots} and {oppOnTarget} for {opp}.',

  // The cards that matter: a red is a name and a minute; two or more bookings
  // of ours are names. One booking is not mentioned — "so what?!" — and nor are
  // theirs short of a red.
  'report.cards.our_red_named':
      '{player} was sent off in the {minute} minute, and {club} finished with '
          'fewer men than they started with.|'
      'A red card for {player} in the {minute} minute left {club} a man short.',
  'report.cards.our_booked_many':
      '{n} {club} players were booked: {names}.|'
      'The referee booked {names} for {club}, {n} cautions in all.',
  'report.cards.their_reds':
      '{opp} had {n} players sent off and finished the match well short of a '
          'full side.|'
      '{n} red cards for {opp}, which shaped everything after them.',

  // Our changes, in one sentence. `{list}` is "Jones for Smith (60th), Brown
  // (75th)" and so on, joined with "and".
  'report.subs.made':
      '{club} made {n} change{s}: {list}.|'
      'From the bench for {club}: {list}.',

  // What was played. `{tactic}` is the strip's own name for it — Balanced,
  // Defence, High Press — so the sentence has to read with a noun in it.
  'report.tactic.started':
      '{club} began the match with {tactic}.|'
      '{tactic} was where {club} started.',
  'report.tactic.switch':
      '{club} switched to {tactic} in the {minute} minute.|'
      'In the {minute} minute {club} changed to {tactic}.',
};
