// Generates src/tokens/tiers.gen.ts from the Dart dump. Edit the dump, never
// the output. Run from the design-system dir:
//   node tool/gen_tiers.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const { tiers } = JSON.parse(readFileSync('fixtures/kit_tokens.json', 'utf8'));

// CSS measures its angle clockwise from "to top", which is what linear-gradient
// takes, so the catalogue's degrees carry over verbatim.
const grad = (g) =>
  `{ angleDeg: ${g.angleDeg}, stops: [${g.stops
    .map(([c, at]) => `['${c}', ${at}]`)
    .join(', ')}] }`;

const body = Object.entries(tiers)
  .map(([tier, t]) => `  ${tier}: {
    bg: ${grad(t.bg)},
    bgLight: ${grad(t.bgLight)},
    accent: '${t.accent}',
    accentLight: '${t.accentLight}',
    labelBg: '${t.labelBg}',
    label: ${JSON.stringify(t.label)},
    emoji: ${JSON.stringify(t.emoji)},
  },`)
  .join('\n');

writeFileSync('src/tokens/tiers.gen.ts', `// GENERATED by tool/gen_tiers.mjs from lib/data/card_theme.dart. Do not edit.
export type TierGradient = { angleDeg: number; stops: [string, number][] };

export interface TierTheme {
  bg: TierGradient;
  bgLight: TierGradient;
  accent: string;
  accentLight: string;
  labelBg: string;
  label: string;
  emoji: string;
}

export const tierThemes: Record<number, TierTheme> = {
${body}
};

/** The tier body as a CSS gradient. Stops are percentages in the catalogue. */
export const tierGradientCss = (g: TierGradient): string =>
  \`linear-gradient(\${g.angleDeg}deg, \${g.stops.map(([c, at]) => \`\${c} \${at}%\`).join(', ')})\`;
`);
console.log('wrote src/tokens/tiers.gen.ts');
